In [5]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

0.12.1


In [10]:
x = 2;
y = 2;
op1 = tf.add(x,y)
op2 = tf.mul(x,y)
op3 = tf.pow(x,op2)

#sess = tf.Session()
#print( sess.run(op3) )

with tf.Session() as sess:
    print( sess.run([op3, op2 ]) )



[16, 4]


In [13]:

g = tf.Graph()
with g.as_default():
    x = tf.add(3,5)

sess = tf.Session( graph=g )
print(sess.run(x))
sess.close()


8


In [2]:
# tensorboard
# !tensorboard --logdir="./graphs"

path_logs = './graphs'

#
# -a +-----+
#    | add | --
# -b +-----+
#

a = tf.constant(2, name='a');
b = tf.constant(3, name='b');
x = tf.add(a,b, name='add')

with tf.Session() as sess:
    write = tf.summary.FileWriter( path_logs, sess.graph )
    print( sess.run(x) )
    
write.close()

5


In [6]:

# constant type
#tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)

a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='dot_product')
with tf.Session() as sess:
    print(sess.run(x))



[[0 2]
 [4 6]]


In [2]:
#tf.zeros(shape, dtype=tf.float32, name=None)

x = tf.zeros([2, 3], tf.int32, name='x') 
y = tf.zeros_like(x, optimize=True, name='y')

print(y)
print(tf.get_default_graph().as_graph_def())

with tf.Session() as sess:
    y = sess.run(y)
    print(y)

Tensor("y:0", shape=(2, 3), dtype=int32)
node {
  name: "x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 3
          }
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "y"
  op: "ZerosLike"
  input: "x"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
versions {
  producer: 17
}

[[0 0 0]
 [0 0 0]]


In [4]:

with tf.Session() as sess:
    print(sess.run(tf.linspace(10.0, 13.0, 4)))
    print(sess.run(tf.range(5)))
    for i in np.arange(5):
        print(i)



[ 10.  11.  12.  13.]
[0 1 2 3 4]
0
1
2
3
4


In [6]:
t_0 = 19 
x = tf.zeros_like(t_0) # ==> 0
y = tf.ones_like(t_0) # ==> 1

with tf.Session() as sess:
    print(sess.run([x, y]))

[0, 1]


In [9]:
t_1 = ['apple', 'peach', 'banana']
x = tf.zeros_like(t_1) # ==> ['' '' '']
#y = tf.ones_like(t_1) # ==> TypeError: Expected string, got 1 of type 'int' instead.

t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]] 
x = tf.zeros_like(t_2) # ==> 2x2 tensor, all elements are False
y = tf.ones_like(t_2) # ==> 2x2 tensor, all elements are True
with tf.Session() as sess:
    print(sess.run([x, y]))


[array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool), array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)]


In [2]:
with tf.variable_scope('meh') as scope:
    a = tf.get_variable('a', [10])
    b = tf.get_variable('b', [100])

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())


In [19]:

#y = 2*x^3
#z = 3 + y^2

#dz/dy = dz/dy*dy/dx
#dz/dy = (2y)*(6x^2) = 12*yx^2
#      = 12*(2*x^3)*x^2
#      = 24*x^5

x = tf.Variable(2.0)
y = 2.0 * (x ** 3)
z = 3.0 + y ** 2
grad_z = tf.gradients(z, [x, y])
with tf.Session() as sess:
    sess.run(x.initializer)
    print(sess.run(grad_z))

x_ = 2.0
print('dz/dy = {}*dy/dx'.format(4*x_**3) )
print('dz/dy = {}'.format(24*x_**5) )


[768.0, 32.0]
dz/dy = 32.0*dy/dx
dz/dy = 768.0


In [25]:

W = tf.Variable(tf.truncated_normal([10,10]), name='W')
with tf.Session() as sess:
    sess.run( W.initializer )
    print(W)
    print( sess.run(W) )


Tensor("W/read:0", shape=(10, 10), dtype=float32)
[[-0.40563682  0.16062029 -0.71486294  0.24939488  0.04161522  0.474022
   1.79872763 -0.49964508  0.16275671 -0.05247218]
 [ 0.74917567 -0.46427971 -0.10228646 -1.86843133 -0.9804033   0.15528598
  -0.81140155  0.61410964  0.74684948  0.48466322]
 [-0.03071053 -0.22619423 -0.19512153 -1.66248596  1.03542316  0.62709397
  -1.04152501 -0.07148623 -0.04174674 -0.12625839]
 [-1.24382877  0.52946997 -0.84973633  0.06872373  1.50142717 -0.37171298
  -0.01037326 -0.08588105  0.08802573  0.1017476 ]
 [ 0.12682524  0.64130563  0.68141538  1.28140152 -0.2666024   0.58476579
  -1.2755065   0.19763047 -0.69266617  0.05350485]
 [ 0.78631306  0.34876707 -0.12141786 -1.05309522  0.41274527 -1.4360677
  -0.6248036  -0.18029913  1.173823   -0.01998813]
 [-0.59159058  0.18904682  1.24058342 -0.20518452 -0.37875903  0.77038735
   0.12067994 -1.51706517  1.31233466 -0.35130689]
 [-0.37181696 -0.65482563  0.49762568 -0.07201093  1.46821725 -0.53847587
   0

In [28]:

W = tf.Variable( 10, name='W' )
op = W.assign( 100 )
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval()) # << 10
    sess.run(op)
    print(W.eval()) #<< 100


10
100


In [30]:

a = tf.Variable( 2, name='a' )
op_times_two = a.assign( 2*a )
with tf.Session() as sess:
    sess.run(a.initializer)
    sess.run(op_times_two); print(a.eval())
    sess.run(op_times_two); print(a.eval())
    sess.run(op_times_two); print(a.eval())



4
8
16


In [3]:
# placeholder

path_logs = './graphs'

a = tf.placeholder( dtype=tf.float32, shape=(3), name='a' )
print(a)

b = tf.constant([1.0,2.0,3.0], dtype=tf.float32, name='b')
print(b)

z = a+b; # tf.add(a,b)
print(z)


with tf.Session() as sess:
    
    writer = tf.summary.FileWriter( path_logs, sess.graph )
    feed_dict = {a:[1,2,3]};
    print(sess.run(z, feed_dict=feed_dict))

writer.close()


Tensor("a_1:0", shape=(3,), dtype=float32)
Tensor("b_1:0", shape=(3,), dtype=float32)
Tensor("add_1:0", shape=(3,), dtype=float32)
[ 2.  4.  6.]


In [9]:

x = tf.constant( [1,2,3,4], dtype=tf.float32 )
y = tf.reduce_mean(x)
with tf.Session() as sess:
    print( sess.run(y) )
print( np.mean( np.array([1,2,3,4]) ) )


2.5
2.5
